# Generated by Django 3.1.4 on 2021-01-03 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=100)),
                ('lenght', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=50)),
                ('TotalSeat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('Seat', models.PositiveIntegerField()),
                ('fin', models.BooleanField()),
                ('MovieName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
