# Generated by Django 3.1.4 on 2021-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fin',
        ),
    ]
